
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Angel
 */
public final class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        this.setTitle("Gestionar Usuarios");
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        newUser = new javax.swing.JButton();
        upDateLogg = new javax.swing.JButton();
        billingButton = new javax.swing.JButton();
        signPanel = new javax.swing.JPanel();
        signUpPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NameFiel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        EmailField = new javax.swing.JTextField();
        emptyField = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        respuesta1Field = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();
        showPassword = new javax.swing.JCheckBox();
        LogUpButton = new javax.swing.JButton();
        usernameExists = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        signInPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnomusuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtresp1 = new javax.swing.JPasswordField();
        txtidusuario = new java.awt.Label();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        LogInButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1199, 699));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 110, 145));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 72));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Panel de Usuarios");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(682, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(62, 62, 62))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        jPanel4.setBackground(new java.awt.Color(0, 150, 136));

        newUser.setBackground(new java.awt.Color(0, 150, 136));
        newUser.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        newUser.setForeground(new java.awt.Color(255, 255, 255));
        newUser.setText("Nuevo Usuario");
        newUser.setToolTipText("Introduce nuevo usuario");
        newUser.setBorder(null);
        newUser.setBorderPainted(false);
        newUser.setContentAreaFilled(false);
        newUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newUser.setOpaque(true);
        newUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newUserMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newUserMouseReleased(evt);
            }
        });
        newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserActionPerformed(evt);
            }
        });

        upDateLogg.setBackground(new java.awt.Color(0, 150, 136));
        upDateLogg.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        upDateLogg.setForeground(new java.awt.Color(255, 255, 255));
        upDateLogg.setText("Actualizar Usuario");
        upDateLogg.setToolTipText("Modificar Usuarios");
        upDateLogg.setBorder(null);
        upDateLogg.setBorderPainted(false);
        upDateLogg.setContentAreaFilled(false);
        upDateLogg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        upDateLogg.setOpaque(true);
        upDateLogg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upDateLoggMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upDateLoggMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upDateLoggMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                upDateLoggMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                upDateLoggMouseReleased(evt);
            }
        });
        upDateLogg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDateLoggActionPerformed(evt);
            }
        });

        billingButton.setBackground(new java.awt.Color(0, 150, 136));
        billingButton.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        billingButton.setForeground(new java.awt.Color(255, 255, 255));
        billingButton.setText("Regresar");
        billingButton.setToolTipText("Regresar al Menú Principal");
        billingButton.setBorder(null);
        billingButton.setBorderPainted(false);
        billingButton.setContentAreaFilled(false);
        billingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        billingButton.setOpaque(true);
        billingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billingButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billingButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billingButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                billingButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                billingButtonMouseReleased(evt);
            }
        });
        billingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(newUser)
                .addGap(34, 34, 34)
                .addComponent(upDateLogg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(719, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upDateLogg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newUser, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1210, 50));

        signPanel.setLayout(new java.awt.CardLayout());

        signUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 77, 64));
        jLabel9.setText("Nombre");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 77, 64));
        jSeparator1.setForeground(new java.awt.Color(0, 77, 64));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator1.setOpaque(true);
        jPanel9.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 310, 2));

        NameFiel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NameFiel.setForeground(new java.awt.Color(0, 77, 64));
        NameFiel.setBorder(null);
        NameFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFielActionPerformed(evt);
            }
        });
        jPanel9.add(NameFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 310, 50));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 77, 64));
        jLabel10.setText("Email");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 77, 64));
        jSeparator2.setForeground(new java.awt.Color(0, 77, 64));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator2.setOpaque(true);
        jPanel9.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 310, 2));

        EmailField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        EmailField.setForeground(new java.awt.Color(0, 77, 64));
        EmailField.setBorder(null);
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });
        jPanel9.add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 310, 50));

        emptyField.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        emptyField.setForeground(new java.awt.Color(255, 51, 0));
        jPanel9.add(emptyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 270, 30));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 77, 64));
        jLabel12.setText("Contraseña");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 77, 64));
        jSeparator4.setForeground(new java.awt.Color(0, 77, 64));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator4.setOpaque(true);
        jPanel9.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 310, 2));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 77, 64));
        jLabel13.setText("¿Ya eres miembro?");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 77, 64));
        jSeparator5.setForeground(new java.awt.Color(0, 77, 64));
        jSeparator5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator5.setOpaque(true);
        jPanel9.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 310, 2));

        respuesta1Field.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        respuesta1Field.setForeground(new java.awt.Color(0, 77, 64));
        respuesta1Field.setBorder(null);
        respuesta1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuesta1FieldActionPerformed(evt);
            }
        });
        jPanel9.add(respuesta1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 310, 50));

        PasswordField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(0, 77, 64));
        PasswordField.setBorder(null);
        jPanel9.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 310, 50));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 77, 64));
        jLabel14.setText("Respuesta de Seguridad (opcional)");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        signInButton.setBackground(new java.awt.Color(255, 255, 255));
        signInButton.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        signInButton.setForeground(new java.awt.Color(0, 150, 136));
        signInButton.setText("Inicia sesión.");
        signInButton.setToolTipText("Sesión ya existente");
        signInButton.setBorderPainted(false);
        signInButton.setContentAreaFilled(false);
        signInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signInButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signInButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signInButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signInButtonMouseReleased(evt);
            }
        });
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        jPanel9.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 502, 170, 30));

        showPassword.setBackground(new java.awt.Color(255, 255, 255));
        showPassword.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        showPassword.setForeground(new java.awt.Color(0, 77, 64));
        showPassword.setToolTipText("Mostrar contraseña");
        showPassword.setBorderPaintedFlat(true);
        showPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showPassword.setPreferredSize(new java.awt.Dimension(30, 30));
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        jPanel9.add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 20, 20));

        LogUpButton.setBackground(new java.awt.Color(0, 77, 64));
        LogUpButton.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        LogUpButton.setForeground(new java.awt.Color(255, 255, 255));
        LogUpButton.setText("Sign Up");
        LogUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LogUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogUpButtonActionPerformed(evt);
            }
        });
        jPanel9.add(LogUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 140, 50));

        usernameExists.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        usernameExists.setForeground(new java.awt.Color(255, 51, 0));
        jPanel9.add(usernameExists, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 160, 30));

        signUpPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 770, 590));

        jPanel5.setBackground(new java.awt.Color(0, 150, 136));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Inicia sesión!");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 149, -1, 168));
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, 168));

        signUpPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 590));

        signPanel.add(signUpPanel, "card6");

        signInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 150, 136));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("ID");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setText("Nombre");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel3.add(txtnomusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 230, -1));

        jLabel4.setText("Correo");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel3.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 230, -1));

        jLabel5.setText("Password");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel3.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 230, -1));

        jLabel6.setText("Pregunta");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel3.add(txtresp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 230, -1));
        jPanel3.add(txtidusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 230, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        signInPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 590));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel6FocusGained(evt);
            }
        });
        jPanel6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel6ComponentShown(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 77, 64));
        jLabel21.setText("¿No te has registrado?");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, -1, -1));

        LogInButton.setBackground(new java.awt.Color(0, 77, 64));
        LogInButton.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        LogInButton.setForeground(new java.awt.Color(255, 255, 255));
        LogInButton.setText("Actualizar");
        LogInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButtonActionPerformed(evt);
            }
        });
        jPanel6.add(LogInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 130, 50));

        signUpButton.setBackground(new java.awt.Color(255, 255, 255));
        signUpButton.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(0, 150, 136));
        signUpButton.setText("Inicia sesión ahora!.");
        signUpButton.setToolTipText("Sesión ya esxistente.");
        signUpButton.setBorderPainted(false);
        signUpButton.setContentAreaFilled(false);
        signUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signUpButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signUpButtonMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpButtonMouseEntered(evt);
            }
        });
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        jPanel6.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 180, 30));

        warningLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        warningLabel.setBorder(null);
        warningLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warningLabelActionPerformed(evt);
            }
        });
        jPanel6.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 310, 50));

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id","Nombre","Correo Electronico", "Contraseña"

            }
        ));
        tbUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbUsuarios.setRowHeight(20);
        tbUsuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseMoved(evt);
            }
        });
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tbUsuarios);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 710, 320));

        signInPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 770, 590));

        signPanel.add(signInPanel, "card7");

        getContentPane().add(signPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1200, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void newUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserMouseClicked

    private void newUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserMouseEntered
        // TODO add your handling code here:;
        newUser.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_newUserMouseEntered

    private void newUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserMouseExited
        // TODO add your handling code here:
        newUser.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_newUserMouseExited

    private void newUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserMousePressed
        // TODO add your handling code here:
        newUser.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_newUserMousePressed

    private void newUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserMouseReleased
        // TODO add your handling code here:
        newUser.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_newUserMouseReleased

    private void newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserActionPerformed
        signPanel.removeAll();
        signPanel.add(signUpPanel);
        signPanel.repaint();
       signPanel.revalidate();
    }//GEN-LAST:event_newUserActionPerformed

    private void upDateLoggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDateLoggMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_upDateLoggMouseClicked

    private void upDateLoggMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDateLoggMouseEntered
        // TODO add your handling code here:
        upDateLogg.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_upDateLoggMouseEntered

    private void upDateLoggMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDateLoggMouseExited
        // TODO add your handling code here:
        upDateLogg.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_upDateLoggMouseExited

    private void upDateLoggMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDateLoggMousePressed
        // TODO add your handling code here:
        upDateLogg.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_upDateLoggMousePressed

    private void upDateLoggMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upDateLoggMouseReleased
        // TODO add your handling code here:
        upDateLogg.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_upDateLoggMouseReleased

    private void upDateLoggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDateLoggActionPerformed
        signPanel.removeAll();
        signPanel.add(signInPanel);
        signPanel.repaint();
        signPanel.revalidate();        
    }//GEN-LAST:event_upDateLoggActionPerformed

    private void billingButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingButtonMousePressed
        // TODO add your handling code here:
        billingButton.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_billingButtonMousePressed

    private void billingButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingButtonMouseReleased
        // TODO add your handling code here:
        billingButton.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_billingButtonMouseReleased

    private void billingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingButtonMouseClicked

    }//GEN-LAST:event_billingButtonMouseClicked

    private void billingButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingButtonMouseExited
        // TODO add your handling code here:
        billingButton.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_billingButtonMouseExited

    private void billingButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingButtonMouseEntered
        // TODO add your handling code here:
        billingButton.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_billingButtonMouseEntered

    private void billingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingButtonActionPerformed
        AdminPanel da = new AdminPanel();
        da.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_billingButtonActionPerformed

    private void NameFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFielActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void respuesta1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuesta1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuesta1FieldActionPerformed

    private void signInButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInButtonMouseEntered
        // TODO add your handling code here:
        signInButton.setForeground(new Color(48, 79, 254));
    }//GEN-LAST:event_signInButtonMouseEntered

    private void signInButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInButtonMouseExited
        // TODO add your handling code here:
        signInButton.setForeground(new Color(0, 150, 136));
    }//GEN-LAST:event_signInButtonMouseExited

    private void signInButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInButtonMousePressed
        // TODO add your handling code here:
        signInButton.setForeground(new Color(0, 77, 64));
    }//GEN-LAST:event_signInButtonMousePressed

    private void signInButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInButtonMouseReleased
        // TODO add your handling code here:
        signInButton.setForeground(new Color(0, 150, 136));
    }//GEN-LAST:event_signInButtonMouseReleased

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        // TODO add your handling code here:
        signPanel.removeAll();
        signPanel.add(signInPanel);
        signPanel.repaint();
        signPanel.revalidate();
    }//GEN-LAST:event_signInButtonActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
        if(showPassword.isSelected()){
            PasswordField.setEchoChar((char)0);
        }
        else
        PasswordField.setEchoChar('*');
    }//GEN-LAST:event_showPasswordActionPerformed

    private void LogUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogUpButtonActionPerformed
        // TODO add your handling code here:
        if(NameFiel.getText().equals("")||EmailField.getText().equals("")
            ||PasswordField.getText().equals(""))
        emptyField.setText("*No deje campo vacio!");
        else{
            int test = ConexionDB.insertToUser(NameFiel.getText(),
                EmailField.getText(), PasswordField.getText(),
                respuesta1Field.getText());

            if(test == 19){
                usernameExists.setText("Usuario existente!");
                emptyField.setText("");
                NameFiel.setText("");
            }

            else{
                
                NameFiel.setText("");
                EmailField.setText("");
                PasswordField.setText("");
                respuesta1Field.setText("");
                emptyField.setText("");
                
            }
            
        }
    }//GEN-LAST:event_LogUpButtonActionPerformed

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
 int ID_Usuario = Integer.parseInt(txtidusuario.getText());
        if (txtidusuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecciona un usuario");
        } else {
            if ((txtnomusuario.getText().isEmpty() || txtemail.getText().isEmpty() || txtpassword.getText().isEmpty() || txtresp1.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Llena todos los campos");
            } else {
                try{
                    ConexionDB.actualizarUsuario(txtnomusuario.getText(),txtemail.getText(), txtpassword.getText(), txtresp1.getText(),ID_Usuario);

                    txtidusuario.setText("");
                    txtnomusuario.setText("");
                    txtemail.setText("");
                    txtpassword.setText("");
                    txtresp1.setText("");
                    mostrarDatos();
                } catch(Exception e){

                    JOptionPane.showMessageDialog(null, "Error en el registro"+e);

                }
            }
        }        

    }//GEN-LAST:event_LogInButtonActionPerformed

    private void signUpButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMousePressed
        // TODO add your handling code here:
        signUpButton.setForeground(new Color(0, 77, 64));
    }//GEN-LAST:event_signUpButtonMousePressed

    private void signUpButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseReleased
        // TODO add your handling code here:
        signUpButton.setForeground(new Color(0, 150, 136));
    }//GEN-LAST:event_signUpButtonMouseReleased

    private void signUpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseExited
        // TODO add your handling code here:
        signUpButton.setForeground(new Color(0, 150, 136));
    }//GEN-LAST:event_signUpButtonMouseExited

    private void signUpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseEntered
        // TODO add your handling code here:
        signUpButton.setForeground(new Color(48, 79, 254));
    }//GEN-LAST:event_signUpButtonMouseEntered

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
        signPanel.removeAll();
        signPanel.add(signUpPanel);
        signPanel.repaint();
        signPanel.revalidate();
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void warningLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warningLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warningLabelActionPerformed

    private void jPanel6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel6FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel6FocusGained

    private void jPanel6ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel6ComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel6ComponentShown

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void tbUsuariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseMoved

    }//GEN-LAST:event_tbUsuariosMouseMoved

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        int fila = tbUsuarios.getSelectedRow();
        if (fila >= 0) {
            txtidusuario.setText(tbUsuarios.getValueAt(fila, 0).toString());
            txtnomusuario.setText(tbUsuarios.getValueAt(fila, 1).toString());
            txtemail.setText(tbUsuarios.getValueAt(fila, 2).toString());
            txtpassword.setText(tbUsuarios.getValueAt(fila, 3).toString());
            txtresp1.setText(tbUsuarios.getValueAt(fila, 4).toString());
        } else {
            JOptionPane.showMessageDialog(null, "No seleccionó fila");
        }
    }//GEN-LAST:event_tbUsuariosMouseClicked

    private void tbUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseEntered
        // Obtener la fila en la que está el mouse
        int row = tbUsuarios.rowAtPoint(evt.getPoint());
        // Seleccionar la fila si no está seleccionada
        if (!tbUsuarios.isRowSelected(row)) {
            tbUsuarios.changeSelection(row, 0, false, false);
        }
    }//GEN-LAST:event_tbUsuariosMouseEntered
    void mostrarDatos() {
        try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/miscelanea_palacios", "root", "");
        Statement stmt = conn.createStatement();
        String sql = "SELECT * FROM usuarios";
        ResultSet rs = stmt.executeQuery(sql);
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID_Usuario");
        model.addColumn("Nombre");
        model.addColumn("Correo Electroico");
        model.addColumn("Password");
        model.addColumn("Respuesta de seguridad");

        
        while (rs.next()) {
            int id = rs.getInt("ID_Usuario");
            String nombre = rs.getString("Nombre");
            String correo = rs.getString("correoElectronico");
            String contraseña = rs.getString("Password");
            String resp1 = rs.getString("respuesta1");

            model.addRow(new Object[] { id, nombre,correo, contraseña, resp1});
        }
        
        tbUsuarios.setModel(model);
        
        rs.close();
        stmt.close();
        conn.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
    }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton LogInButton;
    private javax.swing.JButton LogUpButton;
    private javax.swing.JTextField NameFiel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton billingButton;
    private javax.swing.JLabel emptyField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton newUser;
    private javax.swing.JTextField respuesta1Field;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JButton signInButton;
    private javax.swing.JPanel signInPanel;
    private javax.swing.JPanel signPanel;
    private javax.swing.JButton signUpButton;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTextField txtemail;
    private java.awt.Label txtidusuario;
    private javax.swing.JTextField txtnomusuario;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JPasswordField txtresp1;
    private javax.swing.JButton upDateLogg;
    private javax.swing.JLabel usernameExists;
    private javax.swing.JTextField warningLabel;
    // End of variables declaration//GEN-END:variables
}
